### ISSUE TITLE
Calibrate the sticks for a playstation 4, or only on pc?

### ISSUE THREAD

**Issue by davidxgames** [carpikes/ds4-tools#5]
is this used to calibrate the sticks and use the control on a playstation 4? that is, does it modify the memory of the control?

**Comment by ngth82** [comment]
This is for use on a PC (windows or Linux machine) with Python, and the py libs listed in requirements.txt.

It modifies the contents on the controller and is persistent through power cycles, reset button presses and even a battery pull.

**Comment by carpikes** [comment]
Changes are always in the DS4 memory.
Using only ds4-calibration-tool, changes are not written in the flash, hence they are temporary until a reset or standby.
Using `ds4-tool set-flash-mirror-status 0` before, changes become permanent. I suggest to do `set-flash-mirror-status 1` right after, so that no other changes can be applied by mistake.

**Comment by davidxgames** [comment]
> Changes are always in the DS4 memory. Using only ds4-calibration-tool, changes are not written in the flash, hence they are temporary until a reset or standby. Using `ds4-tool set-flash-mirror-status 0` before, changes become permanent. I suggest to do `set-flash-mirror-status 1` right after, so that no other changes can be applied by mistake.

So the calibration would be seen on the playstation 4?

**Comment by carpikes** [comment]
yes!
